# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

right_arm_controller:
  ros__parameters:
    joints:
      - head_horizontal
      - head_vertical
      - shoulder_vertical_right
      - shoulder_horizontal_right
      - upper_arm_right
      - elbow_right
      - forearm_right
    command_interfaces:
      - position
    state_interfaces:
      - position